runtime: python39  # Specify the Python version
entrypoint: gunicorn -b :$PORT app:app  # Use Gunicorn as the WSGI server

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto

env_variables:
  OPENAI_API_KEY: "your_openai_api_key_here"
